/* Geo PDD*/
SELECT
	LAUNCH_DESCRIPTION ,LAUNCH_CODE ,LAUNCH_DATE , *
FROM
	EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GEOGRAPHY_PRODUCT_LINE_V1
WHERE
	MARKETING_INITIATIVES LIKE '%OLYMPICS%'
	AND GEOGRAPHY_PRODUCT_OFFERING_STATUS_INDICATOR = 'A'
	AND SEASON_YEAR_DESCRIPTION IN ('SU2024', 'FA2024','SP2024');

    SELECT *
FROM
	EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1
WHERE
	MARKETING_INITIATIVES LIKE '%OLYMPICS%'
	AND SEASON_YEAR_DESCRIPTION IN ('SU2024', 'FA2024','SP2024');

    	
SELECT SEASON_YEAR_DESCRIPTION,*
FROM
	EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1
WHERE
	MARKETING_INITIATIVES LIKE '%OLYMPICS%';
